### ISSUE TITLE
HG_Config.h - enabling or disabling saving money gives different results in startCash and also affects cash hint

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#3]
I've been so far playing with the tutorial mission you have kindly provided for anyone to test the shop system, so this report comes from experimenting with that mission.

When the user sets **enableSave** to _true_ in HG_Config.h we see this when launching the test mission:
http://s1370.photobucket.com/user/testusah123/media/saveEnabled_cashHint_zpselv37obs.jpg.html
Take note of the cash amount in both the top right and the bottom right corner.

But when the user sets **enableSave** to _false_ in HG_Config.h we see this when launching the test mission:
http://s1370.photobucket.com/user/testusah123/media/saveDisabled_cashHint_zpssdw1tfnz.jpg.html
Take note of the cash amount in the bottom right corner and what is displayed in the top right corner.

It seems that when saving money has been **enabled** the mission doesn't take into account what has been set as **startCash** in HG_Config.h It also seems to affect that the current cash is displayed correctly in the info hint box.

But when saving money has been **disabled** the mission takes into account what has been set as **startCash** in HG_Config.h. But then on the other hand disabling saving money seems to have a somewhat negative effect on what gets displayed in the info hint box.

**Comment by Ppgtjmad** [comment]
Hey,

> When the user sets enableSave to true in HG_Config.h we see this when launching the test mission:
http://s1370.photobucket.com/user/testusah123/media/saveEnabled_cashHint_zpselv37obs.jpg.html
Take note of the cash amount in both the top right and the bottom right corner.

That's because it takes the money from the old saved variable in **profileNamespace**. The negative value is "normal" because there is no check when adding or subtracting money if the new total is either negative or positive.

If you **enableSave** once, money is stored in profile, if you delete the mission the value will still be in your profile (and persistent through missions until it's nil'd) that's why there's a parameter to reset money from **profileNamespace** -> see **resetSavedMoney**

> But when the user sets enableSave to false in HG_Config.h we see this when launching the test mission:
http://s1370.photobucket.com/user/testusah123/media/saveDisabled_cashHint_zpssdw1tfnz.jpg.html
Take note of the cash amount in the bottom right corner and what is displayed in the top right corner.

Fixed hint, function name wasn't right (hence why you get "You have any"). Cash in HUD is correct (it takes **startCash** when **enableSave** is false).

> It seems that when saving money has been enabled the mission doesn't take into account what has been set as startCash in HG_Config.h It also seems to affect that the current cash is displayed correctly in the info hint box.

That is normal, when taking saved money **startCash** value is ignored because you get your old money back.

> But when saving money has been disabled the mission takes into account what has been set as startCash in HG_Config.h. But then on the other hand disabling saving money seems to have a somewhat negative effect on what gets displayed in the info hint box.

Yup it takes **startCash** value if disabled. Negative values are supported.

If you have suggestions or need precision am all ears :+1:

**Comment by Asmodeuz** [comment]
> Fixed hint, function name wasn't right (hence why you get "You have any"). Cash in HUD is correct (it takes startCash when enableSave is false).

We did test this and indeed was fixed.

Other stuff was more or less just asking silly questions and then amidst everything that there was an actual issue but since that is fixed all is good with this issue. Thanks for the quick response 👍
