### ISSUE TITLE
How do I add items that a trader will buy?

### ISSUE THREAD

**Issue by nanhu888** [Ppgtjmad/SimpleShops#50]
Sorry, this is annoying; but how do you add items that traders will buy? I added some items to HG_TradersCfg.h, but I cannot sell them to merchants. Only the list is displayed, and items cannot be equipped after purchase. @Ppgtjmad

**Comment by nanhu888** [comment]
![2020](https://user-images.githubusercontent.com/62510873/77274931-03365800-6cf2-11ea-8b2a-f96c687057d1.png)

**Comment by Ppgtjmad** [comment]
Hi @nanhu888 

Traders config is **HG_TradersCfg.h**
You can't buy anything from the traders dialog, only selling (list on the right shows what you can sell).

As for the gear shop, rhs weapon classnames are not right, it should be **weap** instead of **weapon**

Check out this comment on my thread https://forums.bohemia.net/forums/topic/187814-release-simple-weapon-shop-system/?page=3&tab=comments#comment-2995798

> They all designate as having weapon rather than weap. One Example being the Glock, it shows it as rhsusf_weapon_glock17g4 When it's ACTUAL classname is rhsusf_weap_glock17g4 This is the same for as far as I've seen. ALL weapons.
